//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNUAL_REVENUE_REPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANNUAL_REVENUE_REPORT()
        {
            this.DETAILED_ANNUAL_REVENUE_REPORT = new HashSet<DETAILED_ANNUAL_REVENUE_REPORT>();
        }
    
        public int Years { get; set; }
        public decimal TotalRevenue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAILED_ANNUAL_REVENUE_REPORT> DETAILED_ANNUAL_REVENUE_REPORT { get; set; }
    }
}
