//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILED_ANNUAL_REVENUE_REPORT
    {
        public int Years { get; set; }
        public int Months { get; set; }
        public int FlightCount { get; set; }
        public decimal Revenue { get; set; }
        public decimal Ratio { get; set; }
    }
}
