//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT_DETAIL
    {
        public string PreventiveAirportID { get; set; }
        public string FlightID { get; set; }
        public int StopoverDuration { get; set; }
        public string Note { get; set; }
    
        public virtual AIRPORT AIRPORT { get; set; }
        public virtual FLIGHT FLIGHT { get; set; }
    }
}
