//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHTDETAIL
    {
        public string AirportCode { get; set; }
        public string FlightCode { get; set; }
        public Nullable<System.TimeSpan> DelayTime { get; set; }
        public string Notes { get; set; }
    
        public virtual AIRPORT AIRPORT { get; set; }
        public virtual FLIGHT FLIGHT { get; set; }
    }
}
