//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightTicketManagementEntities : DbContext
    {
        public FlightTicketManagementEntities()
            : base("name=FlightTicketManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<AIRPORT> AIRPORTs { get; set; }
        public virtual DbSet<ANNUAL_REVENUE_REPORT> ANNUAL_REVENUE_REPORT { get; set; }
        public virtual DbSet<DETAILED_ANNUAL_REVENUE_REPORT> DETAILED_ANNUAL_REVENUE_REPORT { get; set; }
        public virtual DbSet<DETAILED_MONTHLY_REVENUE_REPORT> DETAILED_MONTHLY_REVENUE_REPORT { get; set; }
        public virtual DbSet<FLIGHT> FLIGHTs { get; set; }
        public virtual DbSet<FLIGHT_DETAIL> FLIGHT_DETAIL { get; set; }
        public virtual DbSet<FLIGHT_TICKET> FLIGHT_TICKET { get; set; }
        public virtual DbSet<FLIGHT_TICKET_CLASS_DETAIL> FLIGHT_TICKET_CLASS_DETAIL { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<PLANE> PLANEs { get; set; }
        public virtual DbSet<SEAT> SEATs { get; set; }
        public virtual DbSet<TICKET_CLASS> TICKET_CLASS { get; set; }
    }
}
