//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLIGHT()
        {
            this.FLIGHTDETAILs = new HashSet<FLIGHTDETAIL>();
        }
    
        public string FlightCode { get; set; }
        public string DepartureAirportCode { get; set; }
        public string DestinationAirportCode { get; set; }
        public string PlaneCode { get; set; }
        public Nullable<decimal> TicketPrice { get; set; }
        public Nullable<System.DateTime> DateTimeScheduled { get; set; }
        public Nullable<System.TimeSpan> FlightDuration { get; set; }
    
        public virtual AIRPORT AIRPORT { get; set; }
        public virtual AIRPORT AIRPORT1 { get; set; }
        public virtual PLANE PLANE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLIGHTDETAIL> FLIGHTDETAILs { get; set; }
    }
}
