//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public string ParametersID { get; set; }
        public int MinimumFlightTime { get; set; }
        public int MaxPreventiveAirports { get; set; }
        public int MinimumStopoverTime { get; set; }
        public int MaximumStopoverTime { get; set; }
        public int EarliestBookingTime { get; set; }
        public int LatestBookingCancellationTime { get; set; }
    }
}
