//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airline_ticket_sales_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGULATION
    {
        public string RegulationsCode { get; set; }
        public int MinimumFlightTime { get; set; }
        public int MaxDelayAirports { get; set; }
        public int MinimumDelayTime { get; set; }
        public int MaximumDelayTime { get; set; }
        public int LatestBookingTime { get; set; }
        public int LatestCancellationTime { get; set; }
    }
}
